name = "WagnerModel"
uuid = "1d7a245b-62d6-4e0d-9535-4e5d170b83e8"
authors = ["Harrison Oatman <hroatman@college.harvard.edu> and contributors"]
version = "0.1.0"

[deps]
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ConfParser = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
